name: Deploy with Docker Compose

on:
  push:
    branches: ["dev", "master", "rbh-auth", "tribes-included"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose -f docker/docker-compose.yml up -d --build
