name: Deploy with Docker Compose

on:
  pull_request:
    branches: ["dev"]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy-dev:
    if: github.event.pull_request.base.ref == 'dev'
    runs-on: [self-hosted, dev-rbh-amay]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to dev
        run: |
          docker compose -f docker/docker-compose.yml up -d --build
