name: Deploy to prod

on:
  pull_request:
    branches: ["prod-internal"]
    types:
      - closed

jobs:
  deploy-prod:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, prod-rbh-duel]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Deploy the final state of prod-internal
          ref: prod-internal

      - name: Create .env file
        run: |
          rm -f docker/.env
          cat > docker/.env << EOF
          HTTP_PORT=8080
          BACKEND_PORT=5005
          MONKEYTYPE_FRONTENDURL=https://monkeytype.rbh.makerspace.tools
          MONKEYTYPE_BACKENDURL=https://api.monkeytype.rbh.makerspace.tools
          RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET=${{ secrets.RECAPTCHA_SECRET }}
          FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }}
          FIREBASE_AUTHDOMAIN=${{ secrets.FIREBASE_AUTHDOMAIN }}
          FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }}
          FIREBASE_STORAGEBUCKET=${{ secrets.FIREBASE_STORAGEBUCKET }}
          FIREBASE_MESSAGINGSENDERID=${{ secrets.FIREBASE_MESSAGINGSENDERID }}
          FIREBASE_APPID=${{ secrets.FIREBASE_APPID }}
          EOF
          
      - name: Create frontend .env file
        run: |
          rm -f frontend/.env
          cat > frontend/.env << EOF
          FORCE_TRIBE=true
          EOF

      - name: Deploy to prod
        run: |
          docker compose -f docker/docker-compose.yml up -d --build
