name: Deploy to prod

on:
  pull_request:
    branches: ["prod-internal"]
    types:
      - closed

jobs:
  deploy-prod:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, prod-rbh-duel]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Deploy the final state of prod-internal
          ref: prod-internal

      - name: Deploy to prod
        run: |
          docker compose -f docker/docker-compose.yml up -d --build
